2019-04-21 23:04:23.247002: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-04-21 23:04:23.570138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:02:00.0
totalMemory: 15.90GiB freeMemory: 7.71GiB
2019-04-21 23:04:23.570195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-04-21 23:04:24.414288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-21 23:04:24.414342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-04-21 23:04:24.414349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-04-21 23:04:24.414598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7445 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:02:00.0, compute capability: 6.0)
Using TensorFlow backend.
Namespace(BN=1, cnn=6, gpu='0', len_global=7, len_local=7, lr=0.0001, nb_stacks=2, neighbor_size=3, res=12, tcn=2)

 Load data elapsed time : 5.782 seconds

==============================
Traceback (most recent call last):
  File "tcn.py", line 105, in <module>
    template.run(param_dict)
  File "/home/ryj/renyajie/exp/GLST_Net/template.py", line 53, in run
    model = build_model(func(param_dict['model'][2]), param_dict['lr'])
  File "/home/ryj/renyajie/exp/GLST_Net/template.py", line 37, in build_model
    model.compile(loss='mse', optimizer=adam, metrics=[rmse, mape])
  File "/home/ryj/anaconda3/envs/ryj_keras/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/training.py", line 454, in compile
    handle_metrics(output_metrics)
  File "/home/ryj/anaconda3/envs/ryj_keras/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/training.py", line 423, in handle_metrics
    mask=masks[i])
  File "/home/ryj/anaconda3/envs/ryj_keras/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/training_utils.py", line 428, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/ryj/renyajie/exp/GLST_Net/template.py", line 32, in mape
    mean_value = np.mean(y_true)
  File "/home/ryj/anaconda3/envs/ryj_keras/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2909, in mean
    out=out, **kwargs)
  File "/home/ryj/anaconda3/envs/ryj_keras/lib/python3.6/site-packages/numpy/core/_methods.py", line 80, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'DType' object has no attribute 'type'
